version: '3.5'

services:
    php:
        build:
            context: .
            dockerfile: dockerfile
        container_name: backend
        restart: always
        volumes:
            - "{{ backend_dir }}:/code"
            - ./php.ini:/usr/local/etc/php/php.ini
        working_dir: /code
    composer:
        image: composer:1.9.0
        container_name: composer
        restart: 'no'
        volumes:
            - "{{ backend_dir }}:/code"
        working_dir: /code
        depends_on:
            - php
    nginx:
        image: nginx:latest
        container_name: api_server
        ports:
            - "81:80"
        restart: always
        volumes:
            - "{{ backend_dir }}:/code"
            - ./site.conf:/etc/nginx/conf.d/default.conf